apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectorelastic-deployment
spec:
  selector:
    matchLabels:
      app: projectorelastic-pod
  template:
    metadata:
      labels:
        app: projectorelastic-pod
    spec:
      containers:
      - name: projectorelastic-container
        image: projectorelastic:k8s
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: projectorelastic-service
spec:
  type: LoadBalancer
  selector:
    app: projectorelastic-pod
  ports:
  - port: 58080
    targetPort: 80